export const CATEGORIES = [
  'Nshima', 'Fast Food', 'Vegetables', 'Coffee', 'Drinks', 'Bakery', 'Snacks', 'Ice-cream',
];

export const DEFAULT_MENU = [
  { id: 'ns1', name: 'Nshima & Chicken', category: 'Nshima', price: 60, hasSize: false, stock: 20, available: true },
  { id: 'ns2', name: 'Nshima & Beef', category: 'Nshima', price: 55, hasSize: false, stock: 20, available: true },
  { id: 'ns3', name: 'Nshima & Fish', category: 'Nshima', price: 50, hasSize: false, stock: 15, available: true },
  { id: 'ns4', name: 'Nshima & T-Bone', category: 'Nshima', price: 75, hasSize: false, stock: 10, available: true },
  { id: 'ns5', name: 'Nshima & Pork', category: 'Nshima', price: 65, hasSize: false, stock: 12, available: true },
  { id: 'ff1', name: 'Chips', category: 'Fast Food', price: 25, hasSize: false, stock: 30, available: true },
  { id: 'ff2', name: 'Chicken (Quarter)', category: 'Fast Food', price: 45, hasSize: false, stock: 20, available: true },
  { id: 'ff3', name: 'Chicken (Half)', category: 'Fast Food', price: 80, hasSize: false, stock: 15, available: true },
  { id: 'v1', name: 'Rape', category: 'Vegetables', price: 15, hasSize: false, stock: 25, available: true },
  { id: 'v2', name: 'Chinese', category: 'Vegetables', price: 15, hasSize: false, stock: 25, available: true },
  { id: 'v3', name: 'Kalembula', category: 'Vegetables', price: 15, hasSize: false, stock: 20, available: true },
  { id: 'v4', name: 'Kataapa', category: 'Vegetables', price: 15, hasSize: false, stock: 20, available: true },
  { id: 'v5', name: 'Chiwawa', category: 'Vegetables', price: 15, hasSize: false, stock: 20, available: true },
  { id: 'v6', name: 'Lumanda', category: 'Vegetables', price: 15, hasSize: false, stock: 20, available: true },
  { id: 'cf1', name: 'Latte', category: 'Coffee', price: 25, hasSize: true, stock: 30, available: true },
  { id: 'cf2', name: 'Cappuccino', category: 'Coffee', price: 25, hasSize: true, stock: 30, available: true },
  { id: 'cf3', name: 'Mocha', category: 'Coffee', price: 28, hasSize: true, stock: 25, available: true },
  { id: 'cf4', name: 'Americano', category: 'Coffee', price: 20, hasSize: true, stock: 30, available: true },
  { id: 'cf5', name: 'Iced Coffee', category: 'Coffee', price: 30, hasSize: true, stock: 20, available: true },
  { id: 'dr1', name: 'Soft Drink', category: 'Drinks', price: 15, hasSize: false, stock: 40, available: true },
  { id: 'dr2', name: 'Bottled Water', category: 'Drinks', price: 10, hasSize: false, stock: 40, available: true },
  { id: 'dr3', name: 'Fresh Juice', category: 'Drinks', price: 18, hasSize: false, stock: 20, available: true },
  { id: 'bk1', name: 'Cake (Slice)', category: 'Bakery', price: 35, hasSize: false, stock: 15, available: true },
  { id: 'bk2', name: 'Scone', category: 'Bakery', price: 15, hasSize: false, stock: 20, available: true },
  { id: 'bk3', name: 'Cupcake', category: 'Bakery', price: 20, hasSize: false, stock: 18, available: true },
  { id: 'bk4', name: 'Cookies (Pack)', category: 'Bakery', price: 18, hasSize: false, stock: 20, available: true },
  { id: 'sn1', name: 'Samoosas (3pcs)', category: 'Snacks', price: 25, hasSize: false, stock: 25, available: true },
  { id: 'ic1', name: 'Ice-cream Scoop', category: 'Ice-cream', price: 20, hasSize: false, stock: 20, available: true },
];
